### ISSUE TITLE
Registering with fsspec, and speed relative to SFTP

### ISSUE THREAD

**Issue by dongreenberg** [fsspec/sshfs#25]
Hi - I'm interested in using sshfs as a faster alternative to the builtin sftp filesystem in fsspec (and also need server side copy) in [Runhouse](https://github.com/run-house/runhouse), a compute and data sharing layer for ML. It appears to me that sshfs still is not built-into fsspec and I need to register it as suggested [here](https://github.com/fsspec/filesystem_spec/issues/1071#issuecomment-1275057610) to use it with apis like `fsspec.open()`. A few questions I couldn't figure out:
1. Why has sshfs not yet been made a builtin implementation of fsspec, nor register itself upon installation like other non-builtins? Is it due to some stability or hardness bar it hasn't yet reached?
2. Will it indeed be faster than the builtin SFTPFileSystem? I see that SSHFileSystem is faster than Paramiko, but can't tell if there's any reason it'd be faster than SFTP.

**Comment by efiop** [comment]
Hey @dongreenberg . Thank you for your interest!

sshfs was developed as a part of https://github.com/iterative/dvc and we were not sure that we are ready to submit it as a defeault one to fsspec.

As pointed out in that discussion, we could try doing that now. If you are interested in contributing, feel free to submit a PR for that. Especially if you plan on using sshfs.

Regarding the performance, sftpfilesystem is also paramiko-based and sshfs is based on an amazing project https://github.com/ronf/asyncssh . I don't remember any particular benchmarks from the top of my head, but we've had our fair share of struggle with paramiko in dvc and when implementing sshfs we did see much better performance when downloading/uploading as well as much better overall stability (asyncssh is miles ahead of paramiko in terms of overall quality). Another benefit of sshfs is that it is async-capable (again thanks to asyncssh).

**Comment by dongreenberg** [comment]
I would be interested! What would be needed for such a PR? 

I can also do a smaller step of just adding the standard fsspec registeration call in the sshfs package to make SSHFileSystem the filesystem for "ssh" if the user has sshfs installed. That would be intuitive behavior to me, and would mean that we don't need to deal with some kind of migration from the behavior of the SFTPFileSystem which is registered for 'ssh' in fsspec today (For example, SSHFileSystem expects credentials in a slightly different format that SFTPFileSystem). WDYT?

**Comment by efiop** [comment]
@dongreenberg It would be something like https://github.com/fsspec/filesystem_spec/pull/952 The time consuming part is using sshfs and trying to pinpoint what it lacks.

**Comment by NotSpecial** [comment]
@dongreenberg With the above PR merged and latest release, sshfs now automatically registers with fsspec.

If it's still relevant to you, you could give it a try!
